# Generated by Django 5.1.2 on 2025-02-03 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='date',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='time',
        ),
        migrations.AddField(
            model_name='employee',
            name='agendas',
            field=models.ManyToManyField(related_name='agendas', to='business.agenda'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='agenda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='business.agenda'),
        ),
    ]
