# Generated by Django 5.1.2 on 2025-02-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_agenda_date_remove_agenda_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='agendas',
        ),
        migrations.AddField(
            model_name='agenda',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='business.service'),
        ),
    ]
