# Generated by Django 5.1.2 on 2025-02-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_business_users'),
        ('client', '0002_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='client.client'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
