# Generated by Django 5.1.2 on 2025-02-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_schedule_user_id'),
        ('client', '0002_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='client.client'),
        ),
    ]
