# Generated by Django 5.1.2 on 2025-02-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_schedule_business_alter_schedule_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user_name',
        ),
    ]
