# Generated by Django 5.1.6 on 2025-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_remove_schedule_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='service',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
