# Generated by Django 5.1.6 on 2025-04-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_remove_business_users_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
